// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using persistence;

namespace persistence.Migrations
{
    [DbContext(typeof(ThemisContext))]
    [Migration("20190208184821_added-basic-seed")]
    partial class addedbasicseed
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.1-servicing-10028");

            modelBuilder.Entity("persistence.Chore", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Title");

                    b.HasKey("Id");

                    b.ToTable("Chores");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Ask Pinky and Brain for details!",
                            Title = "Establish World Domination"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Once you dominate all, declare world peace",
                            Title = "World Peace"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Take your fishing rod and decoys and get some fish.",
                            Title = "Go Fishing"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
